// autogenerated by espresso from c64_action_replay_pla.txt
`default_nettype none
`timescale 1 ns / 1 ps
module c64_action_replay_pla (
  input wire [7:0] addr,

  output reg o1,
  output reg o2,
  output reg o3,
  output reg o4
);

wire a7, a6, a5, a4, a3, a2, a1, a0;

assign {a7, a6, a5, a4, a3, a2, a1, a0} = addr;

always @(*) begin
  o4 = (a1) || (!a7);

  o3 = (a7 && !a2);

  o2 = (a6 && a5 && !a4 && a3) || (!a6 && !a3) || (!a5 && a0) || (!a0) ||
      (a4) || (!a7);

  o1 = (!a6 && a5 && a4 && a3 && a1 && !a0) || (a5 && !a4 && a3 && a2 && !a1) ||
    (a7 && a6 && a5 && a3 && !a1) || (a6 && a5 && !a4 && a2) ||
    (a5 && a4 && !a3 && !a1) || (a7 && a5 && a4 && !a2) ||
    (a6 && a5 && !a4 && a3) || (!a5 && !a2 && a1) || (!a6 && !a2 && a1) ||
    (!a4 && a0) || (!a7 && !a3) || (!a7 && !a5) || (!a7 && !a6) || (!a5 && a0);
end

endmodule
`default_nettype wire
// vim:ts=2 sw=2 tw=120 et
